search:
  auto-complete:
    keywords:
      - 안녕
      - 하세요
      - 반가워
      - 어린 왕자
      - 나의 라임 오렌지 나무
      - 맥북
      - 맥북 에어
      - 맥북 프로
      - 맥북 M1
      - 맥미니
      - 맥도날드
      - 콜라
      - 사이드
      - 제로 사이다
      - 카멜
      - 커넥터
      - 콘선트
      - 마우스
      - 모니터 암
      - 싱글 모니터